version: '3.3'

services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: myapp-server
    container_name: myapp-node-server
    command: |
      npm run data:import
      npm run server
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    env_file:
         - .env
    environment:
      - NODE_ENV=production
    networks:
      - app-network
  mongo:
    image: mongo:latest
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: myapp-client
    container_name: myapp-react-client
    command: npm run build
    volumes:
      - ./frontend/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local