name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
    - uses: actions/setup-node@v1
    - name: Test the Testcases 
      run: |
        npm install
        npm run build --if-present
    - name: Login to Docker Hub
      run: docker login --username "${{ secrets.Docker_username }}" --password "${{ secrets.Docker_password }}"
    - name: Build the stack
      run: |
        docker login --username "${{ secrets.Docker_username }}" --password "${{ secrets.Docker_password }}"
        docker-compose down
        cd client && docker build . --file Dockerfile --tag ismayil10/react-app
        docker push ismayil10/reactmern:react-app
        cd ..
        cd server && docker build . --file Dockerfile --tag ismayil10/api-server
        cd ..
        docker push ismayil10/reactmern:api-server
        
      env:
        CI: true
    #  docker-compose up --build --remove-orphans    
    # - name: Build the Docker Image 
    #   run: docker build . --file Dockerfile --tag ismayil10/reactmern
    # - name: Push the Docker Image 
    #   run: docker push ismayil10/reactmern
    #   env:
    #     CI: true

    - name: Configure SSH
      run: |
          git config --global user.email "mohammedismayil10@gmail.com"
          git config --global user.name "mohammedismayil"
          eval $(ssh-agent -s)
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add -
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName "${{ secrets.SSH_HOST }}"
            User "${{ secrets.SSH_USER }}"
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
    - name: Starting the Docker compose
      run: |
         ssh staging 'docker pull registry.hub.docker.com/ismayil10/reactmern:react-app'
         ssh staging 'docker pull registry.hub.docker.com/ismayil10/reactmern:api-server'
         ssh staging 'docker run -d -p 5000:5000 api-server'
         ssh staging 'docker run -i -d -p 3000:3000 react-app'
        
       
#  ssh staging 'docker-compose down'
#         ssh staging 'cd client && docker build -t react-app .'
#         ssh staging 'cd ..'
#         ssh staging 'cd server && docker build -t api-server . ''
#         ssh staging 'cd ..'
#         ssh staging 'docker-compose build'
#         ssh staging 'docker-compose up --build --remove-orphans'
    # - name: push Docker image to Server
    #   run: |
    #        docker pull registry.hub.docker.com/ismayil10/reactmern
    #        docker stop reactmerncontainer || true && docker rm reactmerncontainer || true
    #        docker run -d -p 3001:80 --name reactmerncontainer registry.hub.docker.com/ismayil10/reactmern
    # - run: |
    #    git config --global user.email "mohammedismayil10@gmail.com"
    #    git config --global user.name "mohammedismayil"
    #    eval $(ssh-agent -s) # Run the SSH client 
    #    echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    #    mkdir -p ~/.ssh
    #    chmod 700 ~/.ssh
    #    echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
    #    ssh -o StrictHostKeyChecking=no ec2-user@ec2-13-233-123-151.ap-south-1.compute.amazonaws.com "docker pull registry.hub.docker.com/ismayil10/reactmern"
    #    echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
    #    ssh -o StrictHostKeyChecking=no ec2-user@ec2-13-233-123-151.ap-south-1.compute.amazonaws.com "docker stop reactmerncontainer || true && docker rm reactmerncontainer || true"
    #    ssh -o StrictHostKeyChecking=no ec2-user@ec2-13-233-123-151.ap-south-1.compute.amazonaws.com "docker run -d -p 3001:80 --name reactmerncontainer registry.hub.docker.com/ismayil10/reactmern"    

    #  mkdir -p ~/.ssh/
    #       echo "$SSH_PRIVATE_KEY" > ~/.ssh/staging.key
    #       chmod 600 ~/.ssh/staging.key
    #       cat >>~/.ssh/config <<END
    #       Host staging
    #         HostName $SSH_HOST
    #         User $SSH_USER
    #         IdentityFile ~/.ssh/staging.key
    #         StrictHostKeyChecking no
    #       END
    #       ssh -i "$SSH_PRIVATE_KEY" $SSH_USER@$SSH_HOST

    # ssh -o StrictHostKeyChecking=no ec2-user@ec2-13-233-123-151.ap-south-1.compute.amazonaws.com "docker pull registry.hub.docker.com/ismayil10/reactmern"
          # echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
          # echo "🎉 copying the rsa private key from the server should be done properly - not even spaces"
          # ssh -o StrictHostKeyChecking=no ec2-user@ec2-13-233-123-151.ap-south-1.compute.amazonaws.com "docker stop reactmerncontainer || true && docker rm reactmerncontainer || true"
          # ssh -o StrictHostKeyChecking=no ec2-user@ec2-13-233-123-151.ap-south-1.compute.amazonaws.com "docker run -d -p 3001:80 --name reactmerncontainer registry.hub.docker.com/ismayil10/reactmern"    
          # ssh -o StrictHostKeyChecking=no ec2-user@ec2-13-233-123-151.ap-south-1.compute.amazonaws.com "docker system prune --all -f"  