name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
    - uses: actions/setup-node@v1
    - name: Test the Testcases 
      run: |
        npm install
        npm run build --if-present
    - name: Login to Docker Hub
      run: docker login --username "${{ secrets.Docker_username }}" --password "${{ secrets.Docker_password }}"
    - name: Build the Docker Image 
      run: docker build . --file Dockerfile --tag ismayil10/reactmern
    - name: Push the Docker Image 
      run: docker push ismayil10/reactmern
      env:
        CI: true
    - run: |
       sudo apt-get install openssh-client
       sudo apt-get install git
       git config --global user.email "mohammedismayil10@gmail.com"
       git config --global user.name "mohammedismayil"
       eval $(ssh-agent -s) # Run the SSH client 
       echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
       mkdir -p ~/.ssh
       chmod 700 ~/.ssh
       ssh -o StrictHostKeyChecking=no ec2-user@ec2-13-233-123-151.ap-south-1.compute.amazonaws.com "docker pull registry.hub.docker.com/ismayil10/reactmern"
       ssh -o StrictHostKeyChecking=no ec2-user@ec2-13-233-123-151.ap-south-1.compute.amazonaws.com "docker stop reactmerncontainer || true && docker rm reactmerncontainer || true"
       ssh -o StrictHostKeyChecking=no ec2-user@ec2-13-233-123-151.ap-south-1.compute.amazonaws.com "docker run -d -p 3001:80 --name reactmerncontainer registry.hub.docker.com/ismayil10/reactmern"    