name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
    - uses: actions/setup-node@v1
    - name: Test the Testcases 
      run: |
        npm install
        npm run build --if-present
    - name: Login to Docker Hub
      run: docker login --username "${{ secrets.Docker_username }}" --password "${{ secrets.Docker_password }}"
    - name: Build the stack
      run: |
        docker login --username "${{ secrets.Docker_username }}" --password "${{ secrets.Docker_password }}"
        cd client && docker build . --file Dockerfile -t ismayil10/react-app
        docker push ismayil10/react-app
        cd ..
        cd server && cd db && docker build . --file Dockerfile -t ismayil10/mongo
        docker push ismayil10/mongo
        cd .. && cd ..
        cd server && docker build . --file Dockerfile -t ismayil10/api-server
        cd ..
        docker push ismayil10/api-server
        
    # env:
    #   CI: true
    #  docker-compose up --build --remove-orphans    
    # - name: Build the Docker Image 
    #   run: docker build . --file Dockerfile --tag ismayil10/reactmern
    # - name: Push the Docker Image 
    #   run: docker push ismayil10/reactmern
    #   env:
    #     CI: true

    - name: Configure SSH
      run: |
          git config --global user.email "mohammedismayil10@gmail.com"
          git config --global user.name "mohammedismayil"
          eval $(ssh-agent -s)
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add -
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName "${{ secrets.SSH_HOST }}"
            User "${{ secrets.SSH_USER }}"
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
    - name: Starting the Docker compose
      run: |
         ssh staging 'docker login --username "${{ secrets.Docker_username }}" --password "${{ secrets.Docker_password }}"'
         ssh staging 'git clone https://github.com/mohammedismayil/reactMERN.git'
         ssh staging 'cd reactMERN'
         ssh staging 'docker-compose build'
         ssh staging 'docker-compose up'
    
# ssh staging 'rm -rfv reactMERN'
#  ssh staging 'docker-compose down'